# LAB 2 

### SPAM Detection - The Naive Bayes Algorithm in Python with Scikit-Learn 
D. Shahrokhian
https://stackabuse.com/the-naive-bayes-algorithm-in-python-with-scikit-learn/

4. Use the data in Tables 13.1  and 13.10  from [1]  and the Naive Bayes for Spam Detection from IAML Edimburg with the D. Shahrokhian code – Quantopian and  Github.  Why are the probabilities obtained with the predict_proba from sklearn different of the probabilities obtained by hand and with the N Lidell code?



In [1]:
import pandas as pd

# Tabla 13.1 
print("*****READING TABLE 13.1******")


df1 = pd.read_table('Tabla13.1',  
                   sep='\t', 
                   header= None ,
                   names=['label', 'message'])
print(df1.head())

#Tabla 13.10
print("*****READING TABLE 13.10******")

df10 = pd.read_table('Tabla13.10',  
                   sep='\t', 
                   header= None ,
                   names=['label', 'message'])
print(df10.head())

print("******READING Table IAM******")


#Tabla IAM

df2 = pd.read_table('IAM',  
                   sep='\t', 
                   header= None ,
                   names=['label', 'message'])
print(df2.head())

*****READING TABLE 13.1******
  label                              message
0   yes              Chinese Beijing Chinese
1   yes             Chinese Chinese Shanghai
2   yes                        Chinese Macao
3    no                  Tokyo Japan Chinese
4   yes  Chinese Chinese Chinese Tokyo Japan
*****READING TABLE 13.10******
  label                message
0   yes         Taipei Taiwan 
1   yes  Macao Taiwan Shanghai
2    no           apan Sapporo
3    no   Sapporo Osaka Taiwan
4    no  Taiwan Taiwan Sapporo
******READING Table IAM******
  label                message
0  spam  send us your password
1   ham    send us your review
2   ham   review your password
3  spam              review us
4  spam     send your password


In [2]:
print("*****Table 13.1******")
df1['label'] = df1.label.map({'yes': 1, 'no': 0})
df1['message'] = df1.message.map(lambda x: x.lower())
print(df1.head())

print("*****Table 13.10******")
df10['label'] = df10.label.map({'yes': 1, 'no': 0})
df10['message'] = df10.message.map(lambda x: x.lower())
print(df10.head())

print("******Table IAM******")
df2['label'] = df2.label.map({'spam': 1, 'ham': 0})
df2['message'] = df2.message.map(lambda x: x.lower())
print(df2.head())


*****Table 13.1******
   label                              message
0      1              chinese beijing chinese
1      1             chinese chinese shanghai
2      1                        chinese macao
3      0                  tokyo japan chinese
4      1  chinese chinese chinese tokyo japan
*****Table 13.10******
   label                message
0      1         taipei taiwan 
1      1  macao taiwan shanghai
2      0           apan sapporo
3      0   sapporo osaka taiwan
4      0  taiwan taiwan sapporo
******Table IAM******
   label                message
0      1  send us your password
1      0    send us your review
2      0   review your password
3      1              review us
4      1     send your password


In [3]:
# https://www.nltk.org/ Natural Language Toolkit
# Punkt Sentence Tokenizer https://www.nltk.org/api/nltk.tokenize.html#module-nltk.tokenize.punkt
import nltk
nltk.download('punkt')
print("*****Table 13.1******")
df1['message'] = df1['message'].apply(nltk.word_tokenize)
print(df1.head())

print("*****Table 13.10******")
df10['message'] = df10['message'].apply(nltk.word_tokenize)
print(df10.head())

print("******Table IAM******")
df2['message'] = df2['message'].apply(nltk.word_tokenize)
print(df2.head())

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/jessicasalas/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
*****Table 13.1******
   label                                    message
0      1                [chinese, beijing, chinese]
1      1               [chinese, chinese, shanghai]
2      1                           [chinese, macao]
3      0                    [tokyo, japan, chinese]
4      1  [chinese, chinese, chinese, tokyo, japan]
*****Table 13.10******
   label                    message
0      1           [taipei, taiwan]
1      1  [macao, taiwan, shanghai]
2      0            [apan, sapporo]
3      0   [sapporo, osaka, taiwan]
4      0  [taiwan, taiwan, sapporo]
******Table IAM******
   label                     message
0      1  [send, us, your, password]
1      0    [send, us, your, review]
2      0    [review, your, password]
3      1                [review, us]
4      1      [send, your, password]


In [4]:
# https://www.nltk.org/api/nltk.stem.html
#https://tartarus.org/martin/PorterStemmer/
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
print("*****Table 13.1******")
df1['message'] = df1['message'].apply(lambda x: [stemmer.stem(y) for y in x]) 
print(df1.head())

print("*****Table 13.10******")
df10['message'] = df10['message'].apply(lambda x: [stemmer.stem(y) for y in x]) 
print(df10.head())

print("******Table IAM******")
df2['message'] = df2['message'].apply(lambda x: [stemmer.stem(y) for y in x]) 
print(df2.head())

*****Table 13.1******
   label                                 message
0      1                  [chines, beij, chines]
1      1              [chines, chines, shanghai]
2      1                         [chines, macao]
3      0                  [tokyo, japan, chines]
4      1  [chines, chines, chines, tokyo, japan]
*****Table 13.10******
   label                    message
0      1           [taipei, taiwan]
1      1  [macao, taiwan, shanghai]
2      0            [apan, sapporo]
3      0   [sapporo, osaka, taiwan]
4      0  [taiwan, taiwan, sapporo]
******Table IAM******
   label                     message
0      1  [send, us, your, password]
1      0    [send, us, your, review]
2      0    [review, your, password]
3      1                [review, us]
4      1      [send, your, password]


In [5]:
# Converts the list of words into space-separated strings
print("*****Table 13.1******")
df1['message'] = df1['message'].apply(lambda x: ' '.join(x))
print(df1.head())
print("*****Table 13.10******")
df10['message'] = df10['message'].apply(lambda x: ' '.join(x))
print(df10.head())

print("******Table IAM******")
df2['message'] = df2['message'].apply(lambda x: ' '.join(x))
print(df2.head())

*****Table 13.1******
   label                           message
0      1                chines beij chines
1      1            chines chines shanghai
2      1                      chines macao
3      0                tokyo japan chines
4      1  chines chines chines tokyo japan
*****Table 13.10******
   label                message
0      1          taipei taiwan
1      1  macao taiwan shanghai
2      0           apan sapporo
3      0   sapporo osaka taiwan
4      0  taiwan taiwan sapporo
******Table IAM******
   label                message
0      1  send us your password
1      0    send us your review
2      0   review your password
3      1              review us
4      1     send your password


In [6]:
# Convert a collection of text documents to a matrix of token counts
# http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
# http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction
# to allow one letter words count_vect = CountVectorizer(token_pattern = r"(?u)\b\w+\b")
from sklearn.feature_extraction.text import CountVectorizer

count_vect1 = CountVectorizer(token_pattern = r"(?u)\b\w+\b") 
counts1 = count_vect1.fit_transform(df1['message'])  
print("*****Table 13.1******")
print(counts1)

count_vect10 = CountVectorizer(token_pattern = r"(?u)\b\w+\b") 
counts10 = count_vect10.fit_transform(df10['message'])  

print("*****Table 13.10******")
print(counts10)


count_vect2 = CountVectorizer(token_pattern = r"(?u)\b\w+\b") 
counts2 = count_vect2.fit_transform(df2['message'])  

print("******Table IAM******")
print(counts2)

*****Table 13.1******
  (0, 0)	1
  (0, 1)	2
  (1, 4)	1
  (1, 1)	2
  (2, 3)	1
  (2, 1)	1
  (3, 2)	1
  (3, 5)	1
  (3, 1)	1
  (4, 2)	1
  (4, 5)	1
  (4, 1)	3
*****Table 13.10******
  (0, 6)	1
  (0, 5)	1
  (1, 4)	1
  (1, 1)	1
  (1, 6)	1
  (2, 3)	1
  (2, 0)	1
  (3, 2)	1
  (3, 3)	1
  (3, 6)	1
  (4, 3)	1
  (4, 6)	2
******Table IAM******
  (0, 2)	1
  (0, 6)	1
  (0, 5)	1
  (0, 4)	1
  (1, 3)	1
  (1, 6)	1
  (1, 5)	1
  (1, 4)	1
  (2, 3)	1
  (2, 2)	1
  (2, 6)	1
  (3, 3)	1
  (3, 5)	1
  (4, 2)	1
  (4, 6)	1
  (4, 4)	1
  (5, 0)	1
  (5, 6)	1
  (5, 5)	1
  (5, 4)	1
  (6, 1)	1
  (6, 3)	1
  (6, 5)	1


In [7]:
print(counts1.shape)
print(counts10.shape)
print(counts2.shape)


(5, 6)
(5, 7)
(7, 7)


# TRAINING MODEL FOR TABLE 13.1

In [8]:
# https://stackoverflow.com/questions/28064634/random-state-pseudo-random-numberin-scikit-learn
from sklearn.model_selection import train_test_split
print("The model for Table 13.1 ")
X_train, X_test, y_train, y_test = train_test_split(counts1, df1['label'], test_size=0.1, random_state=55, shuffle=False)
#Ajustar los datos al modelo 
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB().fit(X_train, y_train)
#Evaluar  el modelo 
import numpy as np
predicted = model.predict(X_test)
probability = model.predict_proba(X_test)
print(probability)
print('Accurancy is:')
print(np.mean(predicted == y_test))
#Evaluemos la matriz de confusión
from sklearn.metrics import confusion_matrix
print('The confusion matrix is:')
print(confusion_matrix(y_test, predicted))


The model for Table 13.1 
[[0.31024139 0.68975861]]
Accurancy is:
1.0
The confusion matrix is:
[[1]]


In [9]:
import warnings
warnings.filterwarnings("ignore")
per = 0
for i in range(0,10):
    X_train, X_test, y_train, y_test = train_test_split(counts1, df1['label'], test_size=0.2) 
    model = MultinomialNB().fit(X_train, y_train) 

    import numpy as np
    predicted = model.predict(X_test)
    print(np.mean(predicted == y_test))
    per += np.mean(predicted == y_test)

    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test, predicted))

print(y_test.shape)
print(y_test)
print ("average perfromance")
print (per/10.0)

1.0
[[1]]
1.0
[[1]]
1.0
[[1]]
0.0
[[0 1]
 [0 0]]
1.0
[[1]]
1.0
[[1]]
1.0
[[1]]
1.0
[[1]]
0.0
[[0 1]
 [0 0]]
1.0
[[1]]
(1,)
2    1
Name: label, dtype: int64
average perfromance
0.8


In [10]:
per = 0
for i in range(0,10):
    X_train, X_test, y_train, y_test = train_test_split(counts1, df1['label'], test_size=0.5) 
    model = MultinomialNB().fit(X_train, y_train)  


    import numpy as np
    predicted = model.predict(X_test)
    print(np.mean(predicted == y_test))
    per += np.mean(predicted == y_test)

    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test, predicted))

print ("average perfromance")
print (per/10.0)
print(y_test)

0.6666666666666666
[[0 0]
 [1 2]]
0.6666666666666666
[[0 0]
 [1 2]]
0.6666666666666666
[[0 1]
 [0 2]]
0.6666666666666666
[[0 1]
 [0 2]]
0.6666666666666666
[[0 0]
 [1 2]]
0.6666666666666666
[[0 0]
 [1 2]]
0.6666666666666666
[[0 0]
 [1 2]]
0.6666666666666666
[[0 1]
 [0 2]]
0.6666666666666666
[[0 1]
 [0 2]]
0.6666666666666666
[[0 0]
 [1 2]]
average perfromance
0.6666666666666667
2    1
4    1
1    1
Name: label, dtype: int64


# TRAINING MODEL FOR TABLE 13.10

In [11]:
# https://stackoverflow.com/questions/28064634/random-state-pseudo-random-numberin-scikit-learn
from sklearn.model_selection import train_test_split
print("The model for Table 13.10 ")
X_train, X_test, y_train, y_test = train_test_split(counts10, df10['label'], test_size=0.1, random_state=55, shuffle=False)
#Ajustar los datos al modelo 
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB().fit(X_train, y_train)
#Evaluar  el modelo 
import numpy as np
predicted = model.predict(X_test)
probability = model.predict_proba(X_test)
print(probability)
print('Accurancy is:')
print(np.mean(predicted == y_test))
#Evaluemos la matriz de confusión
from sklearn.metrics import confusion_matrix
print('The confusion matrix is:')
print(confusion_matrix(y_test, predicted))

The model for Table 13.10 
[[0.57142857 0.42857143]]
Accurancy is:
1.0
The confusion matrix is:
[[1]]


In [12]:
per = 0
for i in range(0,10):
    X_train, X_test, y_train, y_test = train_test_split(counts10, df10['label'], test_size=0.2) 
    model = MultinomialNB().fit(X_train, y_train) 

    import numpy as np
    predicted = model.predict(X_test)
    print(np.mean(predicted == y_test))
    per += np.mean(predicted == y_test)

    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test, predicted))

print ("average perfromance")
print (per/10.0)

0.0
[[0 0]
 [1 0]]
1.0
[[1]]
1.0
[[1]]
0.0
[[0 0]
 [1 0]]
1.0
[[1]]
1.0
[[1]]
0.0
[[0 0]
 [1 0]]
1.0
[[1]]
1.0
[[1]]
1.0
[[1]]
average perfromance
0.7


In [13]:
per = 0
for i in range(0,10):
    X_train, X_test, y_train, y_test = train_test_split(counts10, df10['label'], test_size=0.5) 
    model = MultinomialNB().fit(X_train, y_train)  


    import numpy as np
    predicted = model.predict(X_test)
    print(np.mean(predicted == y_test))
    per += np.mean(predicted == y_test)

    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test, predicted))

print ("average perfromance")
print (per/10.0)

0.0
[[0 3]
 [0 0]]
0.0
[[0 3]
 [0 0]]
0.3333333333333333
[[1 0]
 [2 0]]
0.0
[[0 3]
 [0 0]]
0.6666666666666666
[[2 0]
 [1 0]]
0.3333333333333333
[[1 0]
 [2 0]]
0.6666666666666666
[[1 1]
 [0 1]]
0.3333333333333333
[[1 0]
 [2 0]]
0.3333333333333333
[[1 0]
 [2 0]]
0.6666666666666666
[[2 0]
 [1 0]]
average perfromance
0.33333333333333337


# TRAINING MODEL FOR IAM

In [14]:
# https://stackoverflow.com/questions/28064634/random-state-pseudo-random-numberin-scikit-learn
from sklearn.model_selection import train_test_split
print("The model for Table 13.10 ")
X_train, X_test, y_train, y_test = train_test_split(counts10, df10['label'], test_size=0.1, random_state=55, shuffle=False)
#Ajustar los datos al modelo 
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB().fit(X_train, y_train)
#Evaluar  el modelo 
import numpy as np
predicted = model.predict(X_test)
probability = model.predict_proba(X_test)
print(probability)
print('Accurancy is:')
print(np.mean(predicted == y_test))
#Evaluemos la matriz de confusión
from sklearn.metrics import confusion_matrix
print('The confusion matrix is:')
print(confusion_matrix(y_test, predicted))

The model for Table 13.10 
[[0.57142857 0.42857143]]
Accurancy is:
1.0
The confusion matrix is:
[[1]]


In [15]:
per = 0
for i in range(0,10):
    X_train, X_test, y_train, y_test = train_test_split(counts10, df10['label'], test_size=0.2) 
    model = MultinomialNB().fit(X_train, y_train) 

    import numpy as np
    predicted = model.predict(X_test)
    print(np.mean(predicted == y_test))
    per += np.mean(predicted == y_test)

    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test, predicted))

print ("average perfromance")
print (per/10.0)

0.0
[[0 0]
 [1 0]]
1.0
[[1]]
1.0
[[1]]
1.0
[[1]]
0.0
[[0 0]
 [1 0]]
1.0
[[1]]
1.0
[[1]]
1.0
[[1]]
1.0
[[1]]
0.0
[[0 0]
 [1 0]]
average perfromance
0.7


In [16]:
per = 0
for i in range(0,10):
    X_train, X_test, y_train, y_test = train_test_split(counts10, df10['label'], test_size=0.5) 
    model = MultinomialNB().fit(X_train, y_train)  


    import numpy as np
    predicted = model.predict(X_test)
    print(np.mean(predicted == y_test))
    per += np.mean(predicted == y_test)

    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test, predicted))

print ("average perfromance")
print (per/10.0)

0.6666666666666666
[[1 1]
 [0 1]]
0.3333333333333333
[[1 0]
 [2 0]]
0.6666666666666666
[[1 1]
 [0 1]]
0.6666666666666666
[[2 0]
 [1 0]]
0.0
[[0 3]
 [0 0]]
0.6666666666666666
[[2 0]
 [1 0]]
0.3333333333333333
[[1 0]
 [2 0]]
0.3333333333333333
[[1 0]
 [2 0]]
0.3333333333333333
[[1 0]
 [2 0]]
0.6666666666666666
[[2 0]
 [1 0]]
average perfromance
0.4666666666666667


## Bernoulli NB classifier 
5. Use the same data in 4 with the D. Shahrokhian code  but using the Bernoulli NB classifier from sklearn and compare results.

## TRAINING MODEL FOR TABLE 13.1

In [17]:
# https://stackoverflow.com/questions/28064634/random-state-pseudo-random-numberin-scikit-learn
from sklearn.model_selection import train_test_split
print("The model for Table 13.1 ")
X_train, X_test, y_train, y_test = train_test_split(counts1, df1['label'], test_size=0.1, random_state=55, shuffle=False)
#Ajustar los datos al modelo 
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB().fit(X_train, y_train)
#Evaluar  el modelo 
import numpy as np
predicted = model.predict(X_test)
probability = model.predict_proba(X_test)
print(probability)
print('Accurancy is:')
print(np.mean(predicted == y_test))
#Evaluemos la matriz de confusión
from sklearn.metrics import confusion_matrix
print('The confusion matrix is:')
print(confusion_matrix(y_test, predicted))

The model for Table 13.1 
[[0.80893321 0.19106679]]
Accurancy is:
0.0
The confusion matrix is:
[[0 0]
 [1 0]]


## TRAINING MODEL FOR TABLE 13.10

In [18]:
# https://stackoverflow.com/questions/28064634/random-state-pseudo-random-numberin-scikit-learn
from sklearn.model_selection import train_test_split
print("The model for Table 13.10 ")
X_train, X_test, y_train, y_test = train_test_split(counts10, df10['label'], test_size=0.1, random_state=55, shuffle=False)
#Ajustar los datos al modelo 
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB().fit(X_train, y_train)
#Evaluar  el modelo 
import numpy as np
predicted = model.predict(X_test)
probability = model.predict_proba(X_test)
print(probability)
print('Accurancy is:')
print(np.mean(predicted == y_test))
#Evaluemos la matriz de confusión
from sklearn.metrics import confusion_matrix
print('The confusion matrix is:')
print(confusion_matrix(y_test, predicted))

The model for Table 13.10 
[[0.75 0.25]]
Accurancy is:
1.0
The confusion matrix is:
[[1]]


# TRAINING MODEL FOR IAM

In [19]:
# https://stackoverflow.com/questions/28064634/random-state-pseudo-random-numberin-scikit-learn
from sklearn.model_selection import train_test_split
print("The model for IAM ")
X_train, X_test, y_train, y_test = train_test_split(counts2, df2['label'], test_size=0.1, random_state=55, shuffle=False)
#Ajustar los datos al modelo 
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB().fit(X_train, y_train)
#Evaluar  el modelo 
import numpy as np
predicted = model.predict(X_test)
probability = model.predict_proba(X_test)
print(probability)
print('Accurancy is:')
print(np.mean(predicted == y_test))
#Evaluemos la matriz de confusión
from sklearn.metrics import confusion_matrix
print('The confusion matrix is:')
print(confusion_matrix(y_test, predicted))

The model for IAM 
[[0.61565168 0.38434832]]
Accurancy is:
1.0
The confusion matrix is:
[[1]]


###### Comparing the results from the exercise that we made by hand and the previous exercise (Lab2, 4)  are iqual. But comparing the results from the previous exercise (Lab2, 4) and this exercise we can infer the results are similars but in this notebook they include a normalization additional and thus these two results are not equal. 