## LAB 2, Exercise6

D. Shahrokhian https://stackabuse.com/the-naive-bayes-algorithm-in-python-with-scikit-learn/
In [1]:


In [1]:
#Reading base Biggie_lyrics
import pandas as pd
import numpy as np

biggie_df = pd.read_csv('./biggie_lyrics.csv', usecols=[1], encoding='latin-1', header=None)


#Reading Base 2pac 
pac_df = pd.read_csv('./2pac_lyrics.csv', usecols=[1], encoding='latin-1', header=None)

In [2]:

#Preprocessing Biggie_lyrics
biggie_df.columns = ["lyrics"]
biggie_df["lyrics"] = biggie_df["lyrics"].str.replace('[^\w\s]','')
biggie_df["lyrics"] = biggie_df["lyrics"].str.lower()
biggie_df.tail()

#Preprocessing Base 2pac 
pac_df.columns = ["lyrics"]
pac_df["lyrics"] = pac_df["lyrics"].str.replace('[^\w\s]','')
pac_df["lyrics"] = pac_df["lyrics"].str.lower()
pac_df.tail()

lyrics
11  i aint got no motherfucking friends\nthats why...
12  troublesome nigga\nhahaha troublesome 19mother...
13  change shit\ni guess change is good for any of...
14  i see no changes wake up in the morning and i ...
15  out on bail fresh out of jail california dream...

In [3]:
biggie_lyrics = biggie_df["lyrics"].values
biggie_lyrics = [ song.split('\n') for song in biggie_lyrics]
biggie_lyrics = [line for song in biggie_lyrics for line in song]
pac_lyrics = pac_df["lyrics"].values
pac_lyrics = [ song.split('\n') for song in pac_lyrics]
pac_lyrics = [line for song in pac_lyrics for line in song]

rap_lines = [] 

for line in biggie_lyrics:
    if len(line.split()) > 3:
        rap_lines.append(np.array([0,str(line)]))
        
for line in pac_lyrics:
    if len(line.split()) > 3:
        rap_lines.append(np.array([1,str(line)]))
        
rap_lines = np.array(rap_lines)

rap_lines = pd.DataFrame(rap_lines)
rap_lines.columns = ["label","line"]
rap_lines['label'] = rap_lines['label'].replace(['0','1'],[0,1])
print(rap_lines.head())

   label                                               line
0      0                                  fuck all you hoes
1      0                            get a grip motherfucker
2      0  yeah this album is dedicated to all the teache...
3      0  id never amount to nothin to all the people th...
4      0  buildings that i was hustlin in front of that ...


In [4]:
import nltk 
nltk.download('punkt')
#Preprocessing Biggie_lyrics

rap_lines["line"] = rap_lines["line"].apply(nltk.word_tokenize)
print(rap_lines)

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/jessicasalas/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
      label                                               line
0         0                             [fuck, all, you, hoes]
1         0                       [get, a, grip, motherfucker]
2         0  [yeah, this, album, is, dedicated, to, all, th...
3         0  [id, never, amount, to, nothin, to, all, the, ...
4         0  [buildings, that, i, was, hustlin, in, front, ...
5         0  [me, when, i, was, just, tryin, to, make, some...
6         0  [and, all, the, niggas, in, the, struggle, you...
7         0           [uhha, its, all, good, baby, baybee, uh]
8         0                           [it, was, all, a, dream]
9         0            [i, used, to, read, word, up, magazine]
10        0  [saltnpepa, and, heavy, d, up, in, the, limous...
11        0                   [hangin, pictures, on, my, wall]
12        0  [every, saturday, rap, atta

In [5]:
# https://www.nltk.org/api/nltk.stem.html
#https://tartarus.org/martin/PorterStemmer/
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
rap_lines["line"] = rap_lines["line"].apply(lambda x: [stemmer.stem(y) for y in x]) 
rap_lines["line"].head()


0                                [fuck, all, you, hoe]
1                           [get, a, grip, motherfuck]
2    [yeah, thi, album, is, dedic, to, all, the, te...
3    [id, never, amount, to, nothin, to, all, the, ...
4    [build, that, i, wa, hustlin, in, front, of, t...
Name: line, dtype: object

In [6]:
# Converts the list of words into space-separated strings
rap_lines["line"] = rap_lines["line"].apply(lambda x: ' '.join(x))
rap_lines["line"].head()

0                                     fuck all you hoe
1                                get a grip motherfuck
2    yeah thi album is dedic to all the teacher tha...
3    id never amount to nothin to all the peopl tha...
4    build that i wa hustlin in front of that call ...
Name: line, dtype: object

In [7]:
# Convert a collection of text documents to a matrix of token counts
# http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
# http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction
# to allow one letter words count_vect = CountVectorizer(token_pattern = r"(?u)\b\w+\b")
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(token_pattern = r"(?u)\b\w+\b") 
counts = count_vect.fit_transform(rap_lines["line"])  
print(counts)
print(counts.shape)

  (0, 1038)	1
  (0, 2519)	1
  (0, 63)	1
  (0, 859)	1
  (1, 1443)	1
  (1, 943)	1
  (1, 19)	1
  (1, 888)	1
  (2, 1371)	1
  (2, 2278)	1
  (2, 2217)	1
  (2, 2192)	1
  (2, 2220)	1
  (2, 2272)	1
  (2, 569)	1
  (2, 1143)	1
  (2, 58)	1
  (2, 2232)	1
  (2, 2511)	1
  (2, 63)	1
  (3, 24)	1
  (3, 1283)	1
  (3, 1609)	1
  (3, 1515)	1
  (3, 80)	1
  :	:
  (1967, 1909)	1
  (1967, 1213)	1
  (1967, 2118)	1
  (1967, 1253)	1
  (1967, 1531)	1
  (1967, 1371)	1
  (1967, 2220)	1
  (1968, 97)	1
  (1968, 149)	1
  (1968, 1848)	1
  (1968, 1527)	1
  (1968, 856)	1
  (1968, 642)	1
  (1968, 124)	1
  (1968, 83)	1
  (1968, 2220)	1
  (1968, 2272)	1
  (1969, 328)	1
  (1969, 2222)	1
  (1969, 1327)	1
  (1969, 2446)	1
  (1969, 1718)	1
  (1969, 2228)	1
  (1969, 642)	1
  (1969, 1143)	1
(1970, 2535)


In [8]:
# https://stackoverflow.com/questions/28064634/random-state-pseudo-random-numberin-scikit-learn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(counts, rap_lines["label"], test_size=0.1, random_state=69)
print(y_test)
print(X_test)

1725    1
176     0
750     0
39      0
421     0
558     0
1168    1
264     0
876     1
908     1
1581    1
1288    1
602     0
1452    1
354     0
11      0
929     1
741     0
826     0
855     0
1473    1
1571    1
984     1
1697    1
1136    1
947     1
642     0
1921    1
800     0
1917    1
       ..
1698    1
1674    1
1375    1
935     1
425     0
1472    1
433     0
1537    1
685     0
1877    1
335     0
1759    1
1516    1
373     0
428     0
1968    1
1460    1
532     0
227     0
1028    1
1269    1
58      0
248     0
1030    1
1682    1
1846    1
780     0
752     0
1244    1
304     0
Name: label, Length: 197, dtype: int64
  (0, 19)	1
  (0, 1371)	1
  (0, 1214)	1
  (0, 2421)	1
  (0, 1385)	1
  (0, 1390)	1
  (0, 1254)	1
  (1, 2393)	1
  (1, 2441)	1
  (1, 2456)	1
  (1, 2019)	1
  (1, 2073)	1
  (1, 925)	1
  (1, 1888)	1
  (1, 1837)	1
  (2, 1096)	1
  (2, 123)	1
  (2, 1269)	1
  (2, 300)	2
  (2, 612)	1
  (2, 1122)	1
  (3, 2232)	1
  (3, 1482)	1
  (3, 1096)	1
  (3, 1144)	1
  :	:
 

In [12]:
#Ajustar los datos al modelo 
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB().fit(X_train, y_train)
#Evaluar  el modelo 
import numpy as np
predicted = model.predict(X_test)
print("The accuracy is : %.10f" % np.mean(predicted == y_test))
#Evaluemos la matriz de precisión 
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predicted))  
yprob = model.predict_proba(X_test)  

The accuracy is : 0.7177664975
[[232 208]
 [ 70 475]]


## CONCLUSIONS:

Comparing the results from N Lidellwith with this code, we can see the accuracy is better in this notebook than the previous notebook 

In [10]:
per = 0
for i in range(0,5):
    X_train, X_test, y_train, y_test = train_test_split(counts, rap_lines["label"], test_size=0.2) 
    model = MultinomialNB().fit(X_train, y_train)  

    import numpy as np
    predicted = model.predict(X_test)
    print(np.mean(predicted == y_test))
    per += np.mean(predicted == y_test)

    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test, predicted))


print ("average perfromance")
print (per/5.0)

0.766497461928934
[[119  50]
 [ 42 183]]
0.7131979695431472
[[ 95  70]
 [ 43 186]]
0.7157360406091371
[[110  77]
 [ 35 172]]
0.6903553299492385
[[105  89]
 [ 33 167]]
0.7055837563451777
[[109  82]
 [ 34 169]]
average perfromance
0.7182741116751268


In [11]:
per = 0
for i in range(0,5):
    X_train, X_test, y_train, y_test = train_test_split(counts, rap_lines["label"], test_size=0.5) 
    model = MultinomialNB().fit(X_train, y_train)  

    import numpy as np
    predicted = model.predict(X_test)
    print(np.mean(predicted == y_test))
    per += np.mean(predicted == y_test)

    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test, predicted))

print ("average perfromance")
print (per/5.0)

0.716751269035533
[[231 216]
 [ 63 475]]
0.6873096446700507
[[206 228]
 [ 80 471]]
0.7076142131979696
[[238 205]
 [ 83 459]]
0.7025380710659899
[[227 195]
 [ 98 465]]
0.7177664974619289
[[232 208]
 [ 70 475]]
average perfromance
0.7063959390862944
